### ISSUE TITLE
Can't convert file because it was originally saved as a Run

### ISSUE THREAD

**Issue by ghoorzehi** [neuromti/tool-load-tms#4]
Using convert_mat() results in the following error, when used with EEG data during TMS intervention from patient screening dataset:
Exception: /tmp/tmpwq3fbgw1/conversion.mat has no content

**Comment by agricolab** [comment]
For one of the offending files you sent me, i received the following error message when directly loading with matlab:
```
>> load("/home/rtgugg/Desktop/explore/Run_1.mat")
Warning: Variable 'run' originally saved as a Run cannot be instantiated as an object and will be read in as a uint32. 
```
This suggest it was saved as an object that is not specified in one of the .m files in  
https://github.com/neuromti/tool-load-tms/tree/master/matprot/ml

**Comment by agricolab** [comment]
Considering the Variable was originally saved as `Run`, we are looking for a file called `Run.m` somewhere in the protocol and code for this experiment.

**Comment by agricolab** [comment]
The Run, Logger, and Trial classes are from the UKT Toolbox, and pertain to basic recording functions. These are from parts of a session which are usually  not pre or post measurements, but part of the intervention or task.

Currently, tool-load-tms does not support conversion of these files. 

The reason for that is that it depends a lot on the type of markers for which you want to cut your segments from the dataset. Please implement this directly in matlab. 

I updated tool-load-tms to give more informative error messages. Additionally, the respective classes are now defined and shipped in `ml/base`

**Comment by agricolab** [comment]
Addresses with https://github.com/neuromti/tool-load-tms/commit/3c0795941899ede498f82cbe76cdfbaed0df8519
